package database

import "time"

// ProposalStatus enumerates the lifecycle states of an improvement proposal.
// There is deliberately no "refining" state — chatting about a proposal does
// not change its lifecycle; only operator approve/reject (or staleness
// detection at approve time) moves it. Re-approving an apply_failed proposal
// retries the apply.
type ProposalStatus string

const (
	ProposalStatusPending     ProposalStatus = "pending"
	ProposalStatusApproved    ProposalStatus = "approved"
	ProposalStatusRejected    ProposalStatus = "rejected"
	ProposalStatusApplyFailed ProposalStatus = "apply_failed"
	ProposalStatusSuperseded  ProposalStatus = "superseded"
)

// Proposal kinds. *_update kinds carry a TargetRef identifying the existing
// entity; *_new kinds leave TargetRef empty.
const (
	ProposalKindRunbookNew        = "runbook_new"
	ProposalKindRunbookUpdate     = "runbook_update"
	ProposalKindMemoryNew         = "memory_new"
	ProposalKindMemoryUpdate      = "memory_update"
	ProposalKindCronNew           = "cron_new"
	ProposalKindCronUpdate        = "cron_update"
	ProposalKindSkillPromptUpdate = "skill_prompt_update"
)

// ValidProposalKinds returns the closed set of proposal kinds, used for
// validation by both the gateway tool and the API layer.
func ValidProposalKinds() []string {
	return []string{
		ProposalKindRunbookNew,
		ProposalKindRunbookUpdate,
		ProposalKindMemoryNew,
		ProposalKindMemoryUpdate,
		ProposalKindCronNew,
		ProposalKindCronUpdate,
		ProposalKindSkillPromptUpdate,
	}
}

// Proposal creator kinds.
const (
	ProposalCreatedByEvaluator = "evaluator"
	ProposalCreatedByOperator  = "operator"
)

// Proposal is a reviewable self-improvement suggestion generated by the
// improvement-evaluator cron (or, later, by operators). CurrentSnapshot and
// ProposedContent hold per-kind JSON documents with identical shapes so the
// UI can render a before/after diff:
//
//	runbook:      {"title": "...", "content": "..."}
//	memory:       {"scope": "...", "type": "...", "name": "...", "description": "...", "body": "..."}
//	cron:         {"name": "...", "schedule": "...", "prompt": "...", "tool_logical_names": ["..."]}
//	skill_prompt: {"skill_name": "...", "prompt": "..."}
//
// TargetRef is interpreted per kind: runbook ID (decimal string), memory
// "scope/name", cron job UUID, or skill name. For *_new kinds it is empty.
//
// CurrentSnapshot is captured server-side by the gateway at creation time for
// runbook/memory/cron kinds. Skill prompts live only on disk in the API
// container, so for skill_prompt_update the API backfills the snapshot lazily
// on first read (list/get). At approve time the live target is compared to
// the snapshot; a mismatch marks the proposal superseded instead of applying
// a change the operator never reviewed.
type Proposal struct {
	ID        uint           `gorm:"primaryKey" json:"id"`
	UUID      string         `gorm:"uniqueIndex;size:36;not null" json:"uuid"`
	Kind      string         `gorm:"size:32;not null;index" json:"kind"`
	Status    ProposalStatus `gorm:"size:16;not null;default:'pending';index" json:"status"`
	Title     string         `gorm:"size:255;not null" json:"title"`
	Reasoning string         `gorm:"type:text" json:"reasoning"`

	TargetRef       string `gorm:"size:512;index" json:"target_ref"`
	CurrentSnapshot string `gorm:"type:text" json:"current_snapshot"`
	ProposedContent string `gorm:"type:text;not null" json:"proposed_content"`

	// SourceIncidentUUIDs holds {"uuids": [...]} — the evidence incidents the
	// evaluator cited. Entries are validated against the incidents table at
	// creation time (hallucination guard).
	SourceIncidentUUIDs JSONB `gorm:"type:jsonb" json:"source_incident_uuids"`

	// EvaluationRunUUID is the incident UUID of the evaluator cron run that
	// created this proposal (stamped from X-Incident-ID by the gateway).
	EvaluationRunUUID string `gorm:"size:36;index" json:"evaluation_run_uuid"`

	// ChatIncidentUUID is the agent invocation backing the refinement chat;
	// empty until the operator sends the first chat message.
	ChatIncidentUUID string `gorm:"size:36" json:"chat_incident_uuid"`

	CreatedBy  string     `gorm:"size:32" json:"created_by"`
	ApplyError string     `gorm:"type:text" json:"apply_error"`
	AppliedAt  *time.Time `json:"applied_at,omitempty"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

func (Proposal) TableName() string {
	return "proposals"
}

// ProposalChatMessage is one turn of the operator↔assistant refinement chat
// for a proposal. Rows are written deterministically by the API handler (the
// operator message before the agent run starts; the assistant message from
// the run's final response), never parsed out of agent logs.
type ProposalChatMessage struct {
	ID           uint      `gorm:"primaryKey" json:"id"`
	ProposalUUID string    `gorm:"size:36;not null;index" json:"proposal_uuid"`
	Role         string    `gorm:"size:16;not null" json:"role"` // "operator" | "assistant"
	Content      string    `gorm:"type:text;not null" json:"content"`
	CreatedAt    time.Time `json:"created_at"`
}

func (ProposalChatMessage) TableName() string {
	return "proposal_chat_messages"
}
