package services

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"github.com/akmatori/akmatori/internal/database"
	"gopkg.in/yaml.v3"
)

// SkillFrontmatter represents the YAML frontmatter of a SKILL.md file
type SkillFrontmatter struct {
	Name        string            `yaml:"name"`
	Description string            `yaml:"description"`
	Metadata    map[string]string `yaml:"metadata,omitempty"`
}

// GetSkillPrompt reads the prompt for a skill
// For incident-manager system skill, returns the hardcoded default
// For regular skills, reads from SKILL.md file
func (s *SkillService) GetSkillPrompt(name string) (string, error) {
	// Incident-manager uses hardcoded prompt (not editable)
	if name == "incident-manager" {
		return database.DefaultIncidentManagerPrompt, nil
	}

	// Regular skill - read from SKILL.md
	skillPath := filepath.Join(s.GetSkillDir(name), "SKILL.md")
	content, err := os.ReadFile(skillPath)
	if err != nil {
		return "", fmt.Errorf("failed to read SKILL.md: %w", err)
	}

	// Parse and extract body (after frontmatter)
	parts := strings.SplitN(string(content), "---", 3)
	if len(parts) >= 3 {
		body := strings.TrimLeft(parts[2], " \t\n\r")
		// Strip auto-generated resource instructions section if present
		body = stripAutoGeneratedSections(body)
		// Remove the single trailing newline added by generateSkillMd file format
		body = strings.TrimSuffix(body, "\n")
		return body, nil
	}
	return string(content), nil
}

// stripAutoGeneratedSections removes auto-generated sections from the skill body
// to get only the user-defined prompt. Strips old "Quick Start" (Python imports),
// the per-scope "Cross-incident Memory" manifest, and the "Assigned Tools" list.
//
// CRITICAL: when generateSkillMd appends `body + memorySection + toolsSection`,
// reading the file back through GetSkillPrompt and feeding that into another
// generateSkillMd call (e.g. RegenerateAllSkillMds at every startup) would
// double-append both auto-generated blocks unless this function strips them.
// Without the memory strip, every restart accumulated a stale manifest copy.
func stripAutoGeneratedSections(body string) string {
	// Strip old-format "Quick Start" section (Python imports from pre-pi-mono era)
	const quickStartMarker = "## Quick Start"
	const endMarker = "---\n"

	if strings.HasPrefix(body, quickStartMarker) {
		idx := strings.Index(body, endMarker)
		if idx == -1 {
			return body
		}
		body = strings.TrimLeft(body[idx+len(endMarker):], " \t\n\r")
		return stripAutoGeneratedSections(body)
	}

	// Strip the cross-incident memory section.
	//
	// Two forms must be handled:
	//   1. "\n\n## Cross-incident Memory\n…"  — section follows user content
	//   2. "## Cross-incident Memory\n…"      — section starts the body
	//
	// Form 2 happens when the user prompt is empty: generateSkillMd writes
	// the section right after the closing `---\n\n`, and GetSkillPrompt's
	// TrimLeft erases the leading whitespace, so the marker no longer has
	// the leading "\n\n" to anchor on. Without form-2 handling the section
	// survives as part of the "prompt" and accumulates on every regen.
	//
	// Order matters: memory comes BEFORE tools in the generated layout, so
	// cutting at the memory marker also removes the tools section. Falling
	// through to the tools strip covers the case where memory was never
	// present (no memoryDir wired).
	const memoryHeader = "## Cross-incident Memory\n"
	if strings.HasPrefix(body, memoryHeader) {
		body = ""
	} else if idx := strings.Index(body, "\n\n"+memoryHeader); idx != -1 {
		body = strings.TrimSpace(body[:idx])
	}

	// Strip new-format "Assigned Tools" section (auto-generated tool list).
	// Same two-form handling as the memory section above.
	const toolsHeader = "## Assigned Tools\n"
	if strings.HasPrefix(body, toolsHeader) {
		body = ""
	} else if idx := strings.Index(body, "\n\n"+toolsHeader); idx != -1 {
		body = strings.TrimSpace(body[:idx])
	}

	return body
}

// UpdateSkillPrompt updates the prompt for a skill
// For incident-manager system skill, this is a no-op (prompt is hardcoded)
// For regular skills, writes to SKILL.md file
func (s *SkillService) UpdateSkillPrompt(name, prompt string) error {
	// Incident-manager prompt is hardcoded, can't be updated
	if name == "incident-manager" {
		return nil
	}

	// Regular skill - write to SKILL.md
	skill, err := s.GetSkill(name)
	if err != nil {
		return err
	}

	// Sync asset symlinks for [[filename]] references in prompt
	if err := s.SyncSkillAssets(name, prompt); err != nil {
		slog.Warn("failed to sync skill assets", "err", err)
		// Continue even if asset sync fails - it's not critical
	}

	// Generate new SKILL.md with updated body and current tools
	tools := s.getSkillTools(name)
	skillMd := s.generateSkillMd(name, skill.Description, prompt, tools)
	skillPath := filepath.Join(s.GetSkillDir(name), "SKILL.md")

	if err := os.WriteFile(skillPath, []byte(skillMd), 0644); err != nil {
		return fmt.Errorf("failed to write SKILL.md: %w", err)
	}

	return nil
}

// generateSkillMd generates a SKILL.md file with YAML frontmatter and user prompt body
// Tools are called via gateway_call through the pi-mono extension, with usage examples per tool type
func (s *SkillService) generateSkillMd(name, description, body string, tools []database.ToolInstance) string {
	frontmatter := SkillFrontmatter{
		Name:        name,
		Description: description,
		Metadata: map[string]string{
			"short-description": truncateString(description, 50),
		},
	}

	yamlBytes, err := yaml.Marshal(frontmatter)
	if err != nil {
		slog.Error("failed to marshal SKILL.md frontmatter", "skill", name, "err", err)
		yamlBytes = []byte(fmt.Sprintf("name: %s\n", name))
	}

	// Transform [[filename]] references to markdown links [filename](assets/filename)
	resolvedBody := s.contextService.ResolveReferencesToMarkdownLinks(body)

	// List assigned tools with gateway_call usage examples for per-skill routing
	var toolsSection strings.Builder
	var enabledTools []database.ToolInstance
	for _, tool := range tools {
		if tool.Enabled && tool.ToolType.ID != 0 {
			enabledTools = append(enabledTools, tool)
		}
	}
	if len(enabledTools) > 0 {
		toolsSection.WriteString("\n\n## Assigned Tools\n")
		toolsSection.WriteString("\nYour assigned tools are listed below with full parameter schemas and gateway_call examples. Use these examples directly — no need to call list_tools_for_tool_type or get_tool_detail for tools listed here.\n")
		toolsSection.WriteString("Use `execute_script` to run multi-step scripts with built-in `gateway_call()` for batch operations.\n")
		for _, tool := range enabledTools {
			logicalName := tool.LogicalName
			if logicalName == "" {
				logicalName = tool.Name
			}
			toolsSection.WriteString(fmt.Sprintf("\n### %s (logical_name: \"%s\", type: %s)\n", tool.Name, logicalName, tool.ToolType.Name))
			if details := extractToolDetails(tool); details != "" {
				toolsSection.WriteString(details)
			}
			toolsSection.WriteString(generateToolUsageExample(tool))
		}
	}

	memorySection := s.renderMemoryRecallSection(name)

	return fmt.Sprintf("---\n%s---\n\n%s%s%s\n", string(yamlBytes), resolvedBody, memorySection, toolsSection.String())
}

// memoryRecallInstruction is the always-on guidance prepended to every scope's
// memory section. It delegates recall to the memory-searcher subagent, which
// runs in its own scoped subprocess against /akmatori/memory/.
const memoryRecallInstruction = "Before answering questions about prior incidents, hosts, tool quirks, or operator " +
	"feedback, delegate the recall to the memory-searcher subagent. It runs in its own scoped subprocess against " +
	"/akmatori/memory/ and returns top file paths with brief excerpts. Read full files directly with the local read " +
	"tool when needed.\n\n" +
	"`subagent({\"agent\": \"memory-searcher\", \"task\": \"<what you want to recall — host name, error pattern, tool quirk, feedback topic>\"})`\n\n" +
	"Cite `Source: <name>` when it helps."

// memoryWriteInstructionTemplate is the end-of-investigation guidance that
// asks the agent to record durable cross-incident facts via the memory-writer
// subagent. The first %s is the scope slug (global for AGENTS.md, skill name
// for SKILL.md); the second %s is the scope slug repeated inside the example.
const memoryWriteInstructionTemplate = "When the investigation surfaces durable cross-incident facts (host quirks, " +
	"recurring incident patterns, tool quirks, validated runbook gaps, or operator feedback) that will speed up " +
	"future troubleshooting, record them by invoking the memory-writer subagent. Pass the full reasoning log as " +
	"`task` along with the directive to save ONLY important, non-obvious information. Use scope `\"%s\"` and the " +
	"originating incident UUID:\n\n" +
	"`subagent({\"agent\": \"memory-writer\", \"task\": \"<full reasoning log and instruction to save only important information that will help speed up troubleshooting next time>\", \"scope\": \"%s\", \"incident\": \"<this incident's UUID>\"})`\n\n" +
	"memory-writer is idempotent — if a memory with the same semantic name already exists, it updates in place. " +
	"Skip the call when nothing durable was learned."

// renderMemoryRecallSection returns the recall instruction plus the on-disk
// MEMORY.md manifest for the given scope ("global" for AGENTS.md, the skill
// name for SKILL.md), followed by the Record durable findings subsection that
// invokes the memory-writer subagent. When the manifest is missing or
// unreadable, only the recall + write instructions are returned — the agent
// can still call memory-searcher and discover entries dynamically. Returns an
// empty string only when the service has no memoryDir configured (defensive;
// should not happen in prod).
func (s *SkillService) renderMemoryRecallSection(scope string) string {
	if s.memoryDir == "" {
		return ""
	}
	manifest := s.readMemoryManifest(scope)

	var b strings.Builder
	b.WriteString("\n\n## Cross-incident Memory\n\n")
	b.WriteString(memoryRecallInstruction)
	b.WriteString("\n")

	if manifest != "" {
		b.WriteString("\n")
		b.WriteString(manifest)
		if !strings.HasSuffix(manifest, "\n") {
			b.WriteString("\n")
		}
	} else {
		b.WriteString("\n_No memories indexed for this scope yet._\n")
	}

	b.WriteString("\n### Record durable findings\n\n")
	b.WriteString(fmt.Sprintf(memoryWriteInstructionTemplate, scope, scope))
	b.WriteString("\n")
	return b.String()
}

// readMemoryManifest returns the on-disk MEMORY.md for a scope, or an empty
// string when the file is missing/unreadable. Errors are logged at debug
// (not warn) because first-run is normal and the agent has a sensible
// fallback (delegate recall to the memory-searcher subagent).
func (s *SkillService) readMemoryManifest(scope string) string {
	if s.memoryDir == "" || scope == "" {
		return ""
	}
	path := filepath.Join(s.memoryDir, scope, "MEMORY.md")
	b, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			slog.Debug("memory manifest unreadable", "scope", scope, "err", err)
		}
		return ""
	}
	return string(b)
}

// sshHasConfiguredHosts checks if the SSH tool instance has any configured hosts.
func sshHasConfiguredHosts(tool database.ToolInstance) bool {
	if tool.Settings == nil {
		return false
	}
	hostsData, ok := tool.Settings["ssh_hosts"]
	if !ok {
		return false
	}
	hostsJSON, err := json.Marshal(hostsData)
	if err != nil {
		return false
	}
	var hosts []map[string]interface{}
	if err := json.Unmarshal(hostsJSON, &hosts); err != nil {
		return false
	}
	for _, h := range hosts {
		if addr, _ := h["address"].(string); strings.TrimSpace(addr) != "" {
			return true
		}
	}
	return false
}

// sshAllHostsAllowWrite checks if ALL hosts in an SSH tool instance have allow_write_commands enabled.
// Returns false if any host is read-only (the default), if settings are missing, or if there are no hosts.
func sshAllHostsAllowWrite(tool database.ToolInstance) bool {
	if tool.Settings == nil {
		return false
	}
	hostsData, ok := tool.Settings["ssh_hosts"]
	if !ok {
		return false
	}
	hostsJSON, err := json.Marshal(hostsData)
	if err != nil {
		return false
	}
	var hosts []map[string]interface{}
	if err := json.Unmarshal(hostsJSON, &hosts); err != nil {
		return false
	}
	if len(hosts) == 0 {
		return false
	}
	hasValidHost := false
	for _, h := range hosts {
		// Skip placeholder rows with blank addresses (same filter as runtime)
		if addr, _ := h["address"].(string); strings.TrimSpace(addr) == "" {
			continue
		}
		hasValidHost = true
		allow, ok := h["allow_write_commands"].(bool)
		if !ok || !allow {
			return false
		}
	}
	return hasValidHost
}

// generateToolUsageExample creates usage examples showing how to call the tool via gateway_call
func generateToolUsageExample(tool database.ToolInstance) string {
	typeName := tool.ToolType.Name
	logicalName := tool.LogicalName
	if logicalName == "" {
		logicalName = tool.Name
	}

	switch typeName {
	case "ssh":
		adhocEnabled, _ := tool.Settings["allow_adhoc_connections"].(bool)
		adhocWriteEnabled, _ := tool.Settings["adhoc_allow_write_commands"].(bool)
		hasConfiguredHosts := sshHasConfiguredHosts(tool)
		configuredHostsWritable := sshAllHostsAllowWrite(tool)

		// If neither configured hosts nor ad-hoc connections are available,
		// the tool is misconfigured — tell the agent explicitly.
		if !hasConfiguredHosts && !adhocEnabled {
			return fmt.Sprintf(`
**SSH tool "%s" is not configured** — no hosts are defined and ad-hoc connections are disabled.
Ask the operator to add SSH hosts or enable ad-hoc connections in the tool settings before this tool can be used.
`, tool.Name)
		}

		// Build read-only warnings separately for configured hosts and ad-hoc
		var readOnlyNote string
		readOnlyCommands := `Allowed: cat, head, tail, grep, find, ls, ps, top, df, free, netstat, ss, uptime,
vmstat, iostat, mpstat, sar, pidstat, journalctl, dmesg, nproc, lscpu, getconf,
docker ps/logs/inspect, kubectl get/describe/logs, systemctl status.
For CPU core count use ` + "`nproc`" + ` or ` + "`lscpu`" + ` (not /proc/cpuinfo parsing).
`
		if hasConfiguredHosts && !configuredHostsWritable && adhocEnabled && adhocWriteEnabled {
			readOnlyNote = "\n**Read-only mode is enabled for configured hosts** — only diagnostic commands are allowed.\n" + readOnlyCommands +
				"Ad-hoc connections allow write commands.\n"
		} else if hasConfiguredHosts && configuredHostsWritable && adhocEnabled && !adhocWriteEnabled {
			readOnlyNote = "\n**Read-only mode is enabled for ad-hoc connections** — only diagnostic commands are allowed on ad-hoc targets.\n" + readOnlyCommands
		} else if !configuredHostsWritable && !(adhocEnabled && adhocWriteEnabled) {
			readOnlyNote = "\n**Read-only mode is enabled** — only diagnostic commands are allowed.\n" + readOnlyCommands
		}

		// Build examples based on what's available
		var configuredExamples string
		if hasConfiguredHosts {
			configuredExamples = fmt.Sprintf(`
gateway_call("ssh.execute_command", {"command": "uptime"}, "%s")
gateway_call("ssh.execute_command", {"command": "df -h", "servers": ["hostname"]}, "%s")
gateway_call("ssh.test_connectivity", {}, "%s")
gateway_call("ssh.get_server_info", {}, "%s")`, logicalName, logicalName, logicalName, logicalName)
		}

		var adhocExample string
		if adhocEnabled {
			adhocExample = fmt.Sprintf(`
# Ad-hoc: connect to any server by hostname/FQDN/IP
gateway_call("ssh.execute_command", {"command": "uptime", "servers": ["<hostname-or-ip>"]}, "%s")
gateway_call("ssh.test_connectivity", {"servers": ["<server1>", "<server2>"]}, "%s")
gateway_call("ssh.get_server_info", {"servers": ["<hostname-or-ip>"]}, "%s")`, logicalName, logicalName, logicalName)
		}

		return fmt.Sprintf(`
**Parameters:**
- `+"`execute_command`"+`: command* | servers
- `+"`test_connectivity`"+`: servers
- `+"`get_server_info`"+`: servers
(* = required)

Usage (via gateway_call):
`+"```"+`
%s%s
`+"```"+`
%s`, configuredExamples, adhocExample, readOnlyNote)
	case "zabbix":
		return fmt.Sprintf(`
**Parameters:**
- `+"`get_hosts`"+`: output, filter, search, start_search, limit
- `+"`get_problems`"+`: recent, severity_min, hostids, limit
- `+"`get_items`"+`: hostids, filter, search, start_search, output, limit
- `+"`get_items_batch`"+`: searches* | hostids, start_search, output, limit_per_search
- `+"`get_history`"+`: itemids* | history, time_from, time_till, limit, sortfield, sortorder
- `+"`get_triggers`"+`: hostids, only_true, min_severity, output
- `+"`api_request`"+`: method* | params
(* = required)

Usage (via gateway_call):
`+"```"+`
gateway_call("zabbix.get_hosts", {}, "%s")
gateway_call("zabbix.get_problems", {"severity_min": 3}, "%s")
gateway_call("zabbix.get_items_batch", {"searches": ["cpu", "memory"]}, "%s")
gateway_call("zabbix.get_history", {"itemids": ["67890"], "limit": 10}, "%s")
gateway_call("zabbix.get_items", {"hostids": ["12345"], "search": {"key_": "cpu"}}, "%s")
gateway_call("zabbix.get_triggers", {"hostids": ["12345"], "only_true": true}, "%s")
gateway_call("zabbix.api_request", {"method": "host.get", "params": {"output": ["hostid", "host"]}}, "%s")
`+"```"+`
`, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName)
	case "victoria_metrics":
		return fmt.Sprintf(`
**Parameters:**
- `+"`instant_query`"+`: query* | time, step, timeout
- `+"`range_query`"+`: query*, start*, end*, step* | timeout
- `+"`label_values`"+`: label_name* | match, start, end
- `+"`series`"+`: match* | start, end
- `+"`api_request`"+`: path* | method, params
(* = required)

Usage (via gateway_call):
`+"```"+`
gateway_call("victoria_metrics.instant_query", {"query": "up"}, "%s")
gateway_call("victoria_metrics.range_query", {"query": "rate(http_requests_total[5m])", "start": "2h", "end": "now", "step": "1m"}, "%s")
gateway_call("victoria_metrics.label_values", {"label_name": "__name__"}, "%s")
gateway_call("victoria_metrics.series", {"match": "up"}, "%s")
gateway_call("victoria_metrics.api_request", {"path": "/api/v1/status/tsdb"}, "%s")
`+"```"+`
`, logicalName, logicalName, logicalName, logicalName, logicalName)
	case "postgresql":
		return fmt.Sprintf(`
**Parameters:**
- `+"`execute_query`"+`: query* | limit
- `+"`list_tables`"+`: schema
- `+"`describe_table`"+`: table_name* | schema
- `+"`get_indexes`"+`: table_name* | schema
- `+"`get_table_stats`"+`: table_name | schema
- `+"`explain_query`"+`: query*
- `+"`get_active_queries`"+`: include_idle, min_duration_seconds
- `+"`get_locks`"+`: blocked_only
- `+"`get_replication_status`"+`: (no parameters)
- `+"`get_database_stats`"+`: (no parameters)
(* = required)

All queries are read-only — INSERT/UPDATE/DELETE/DROP are rejected.

Usage (via gateway_call):
`+"```"+`
gateway_call("postgresql.execute_query", {"query": "SELECT * FROM users LIMIT 10"}, "%s")
gateway_call("postgresql.list_tables", {}, "%s")
gateway_call("postgresql.describe_table", {"table_name": "users"}, "%s")
gateway_call("postgresql.get_active_queries", {}, "%s")
gateway_call("postgresql.get_locks", {"blocked_only": true}, "%s")
gateway_call("postgresql.get_database_stats", {}, "%s")
`+"```"+`
`, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName)
	case "grafana":
		return fmt.Sprintf(`
**Parameters:**
- `+"`search_dashboards`"+`: query, tag, type, folder_id, limit
- `+"`get_dashboard`"+`: uid*
- `+"`get_dashboard_panels`"+`: uid*
- `+"`get_alert_rules`"+`: (no parameters)
- `+"`get_alert_instances`"+`: filter, silenced, inhibited, active
- `+"`get_alert_rule`"+`: uid*
- `+"`silence_alert`"+` **(write)**: matchers*, starts_at*, ends_at*, created_by*, comment*
- `+"`list_data_sources`"+`: (no parameters)
- `+"`query_data_source`"+`: datasource_uid*, queries* | from, to
- `+"`query_prometheus`"+`: datasource_uid*, expr* | start, end, step, instant, range, from, to
- `+"`query_loki`"+`: datasource_uid*, expr* | limit, direction, start, end, from, to
- `+"`create_annotation`"+` **(write)**: text* | dashboard_id, panel_id, tags, time, time_end
- `+"`get_annotations`"+`: from, to, dashboard_id, panel_id, tags, limit, type
(* = required)
**(write)** marks methods that mutate state — only call after confirming intent.

Usage (via gateway_call):
`+"```"+`
gateway_call("grafana.search_dashboards", {"query": "api latency"}, "%s")
gateway_call("grafana.get_dashboard", {"uid": "abc123"}, "%s")
gateway_call("grafana.get_dashboard_panels", {"uid": "abc123"}, "%s")
gateway_call("grafana.list_data_sources", {}, "%s")
gateway_call("grafana.query_prometheus", {"datasource_uid": "prom-uid", "expr": "up", "instant": true}, "%s")
gateway_call("grafana.query_loki", {"datasource_uid": "loki-uid", "expr": "{app=\"api\"} |= \"error\"", "limit": 100}, "%s")
gateway_call("grafana.get_alert_rules", {}, "%s")
gateway_call("grafana.get_alert_instances", {"active": true}, "%s")
`+"```"+`
`, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName)
	case "catchpoint":
		return fmt.Sprintf(`
**Parameters:**
- `+"`get_alerts`"+`: severity, start_time, end_time, test_ids, page_number, page_size
- `+"`get_alert_details`"+`: alert_ids*
- `+"`get_test_performance`"+`: test_ids* | start_time, end_time, metrics, dimensions
- `+"`get_test_performance_raw`"+`: test_ids* | start_time, end_time, node_ids, page_number, page_size
- `+"`get_tests`"+`: test_ids, test_type, folder_id, status, page_number, page_size
- `+"`get_test_details`"+`: test_ids*
- `+"`get_test_errors`"+`: test_ids, start_time, end_time, page_number, page_size
- `+"`get_internet_outages`"+`: start_time, end_time, asn, country, page_number, page_size
- `+"`get_nodes`"+`: page_number, page_size
- `+"`get_node_alerts`"+`: node_ids, start_time, end_time, page_number, page_size
- `+"`acknowledge_alerts`"+` **(write)**: alert_ids*, action* | assignee — `+"`assignee`"+` is required when `+"`action=\"assign\"`"+`
- `+"`run_instant_test`"+` **(write)**: test_id*
(* = required)
**(write)** marks methods that mutate state — only call after confirming intent.

Usage (via gateway_call):
`+"```"+`
gateway_call("catchpoint.get_alerts", {"severity": "critical"}, "%s")
gateway_call("catchpoint.get_alert_details", {"alert_ids": "12345,67890"}, "%s")
gateway_call("catchpoint.get_tests", {}, "%s")
gateway_call("catchpoint.get_test_performance", {"test_ids": "12345", "metrics": "response_time,availability"}, "%s")
gateway_call("catchpoint.get_test_errors", {"test_ids": "12345"}, "%s")
gateway_call("catchpoint.get_internet_outages", {"country": "US"}, "%s")
gateway_call("catchpoint.get_nodes", {}, "%s")
gateway_call("catchpoint.acknowledge_alerts", {"alert_ids": "12345", "action": "acknowledge"}, "%s")
`+"```"+`
`, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName)
	case "pagerduty":
		return fmt.Sprintf(`
**Parameters:**
- `+"`get_incidents`"+`: statuses, urgencies, service_ids, since, until, sort_by, limit, offset
- `+"`get_incident`"+`: incident_id*
- `+"`get_incident_notes`"+`: incident_id*
- `+"`get_incident_alerts`"+`: incident_id*
- `+"`get_services`"+`: query, limit, offset
- `+"`get_on_calls`"+`: schedule_ids, escalation_policy_ids, since, until
- `+"`get_escalation_policies`"+`: query, limit, offset
- `+"`list_recent_changes`"+`: since, until, limit, offset
- `+"`acknowledge_incident`"+` **(write)**: incident_id*, requester_email*
- `+"`resolve_incident`"+` **(write)**: incident_id*, requester_email*
- `+"`reassign_incident`"+` **(write)**: incident_id*, requester_email*, assignee_ids* | escalation_policy_id
- `+"`add_incident_note`"+` **(write)**: incident_id*, requester_email*, content*
- `+"`send_event`"+` **(write)**: routing_key*, event_action* | dedup_key, summary, severity, source, component, group, class, custom_details — `+"`summary`"+` is required when `+"`event_action=\"trigger\"`"+`; `+"`dedup_key`"+` is required when `+"`event_action=\"acknowledge\"`"+` or `+"`\"resolve\"`"+`
(* = required)
**(write)** marks methods that mutate state — only call after confirming intent.

Usage (via gateway_call):
`+"```"+`
gateway_call("pagerduty.get_incidents", {"statuses": "triggered,acknowledged"}, "%s")
gateway_call("pagerduty.get_incident", {"incident_id": "PABC123"}, "%s")
gateway_call("pagerduty.get_incident_notes", {"incident_id": "PABC123"}, "%s")
gateway_call("pagerduty.get_services", {"query": "api"}, "%s")
gateway_call("pagerduty.get_on_calls", {"escalation_policy_ids": "PXYZ987"}, "%s")
gateway_call("pagerduty.acknowledge_incident", {"incident_id": "PABC123", "requester_email": "oncall@example.com"}, "%s")
gateway_call("pagerduty.add_incident_note", {"incident_id": "PABC123", "requester_email": "oncall@example.com", "content": "Investigating elevated 5xx rate"}, "%s")
gateway_call("pagerduty.send_event", {"routing_key": "R0UTINGKEY", "event_action": "trigger", "summary": "Disk usage > 90%%", "severity": "warning"}, "%s")
`+"```"+`
`, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName)
	case "clickhouse":
		return fmt.Sprintf(`
**Parameters:**
- `+"`execute_query`"+`: query* | limit, timeout_seconds
- `+"`show_databases`"+`: (no parameters)
- `+"`show_tables`"+`: database
- `+"`describe_table`"+`: table_name* | database
- `+"`get_query_log`"+`: min_duration_ms, limit, query_kind
- `+"`get_running_queries`"+`: min_elapsed_seconds
- `+"`get_merges`"+`: table, database
- `+"`get_replication_status`"+`: table, database
- `+"`get_parts_info`"+`: table_name* | database, active_only
- `+"`get_cluster_info`"+`: cluster
(* = required)

All queries are read-only — SELECT, WITH, SHOW, DESCRIBE, EXPLAIN, EXISTS only.

Usage (via gateway_call):
`+"```"+`
gateway_call("clickhouse.execute_query", {"query": "SELECT count() FROM system.parts WHERE active"}, "%s")
gateway_call("clickhouse.show_databases", {}, "%s")
gateway_call("clickhouse.describe_table", {"table_name": "events"}, "%s")
gateway_call("clickhouse.get_query_log", {"min_duration_ms": 1000, "limit": 50}, "%s")
gateway_call("clickhouse.get_running_queries", {"min_elapsed_seconds": 5}, "%s")
gateway_call("clickhouse.get_merges", {}, "%s")
gateway_call("clickhouse.get_parts_info", {"table_name": "events", "active_only": true}, "%s")
gateway_call("clickhouse.get_cluster_info", {}, "%s")
`+"```"+`
`, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName)
	case "netbox":
		return fmt.Sprintf(`
**Parameters:**
- `+"`get_devices`"+`: name, site, role, status, tag, platform, tenant, q, limit, offset
- `+"`get_device`"+`: id*
- `+"`get_interfaces`"+`: device, device_id, name, type, enabled, limit, offset
- `+"`get_sites`"+`: name, region, status, tag, tenant, q, limit, offset
- `+"`get_racks`"+`: site, name, status, role, tenant, q, limit, offset
- `+"`get_cables`"+`: device, site, type, status, limit, offset
- `+"`get_device_types`"+`: manufacturer, model, q, limit, offset
- `+"`get_ip_addresses`"+`: address, device, interface, vrf, tenant, status, q, limit, offset
- `+"`get_prefixes`"+`: prefix, site, vrf, vlan, tenant, status, q, limit, offset
- `+"`get_vlans`"+`: vid, name, site, group, tenant, q, limit, offset
- `+"`get_vrfs`"+`: name, tenant, q, limit, offset
- `+"`get_circuits`"+`: provider, type, status, tenant, q, limit, offset
- `+"`get_providers`"+`: name, q, limit, offset
- `+"`get_virtual_machines`"+`: name, cluster, site, status, role, tenant, q, limit, offset
- `+"`get_clusters`"+`: name, type, group, site, tenant, q, limit, offset
- `+"`get_vm_interfaces`"+`: virtual_machine, name, enabled, limit, offset
- `+"`get_tenants`"+`: name, group, q, limit, offset
- `+"`get_tenant_groups`"+`: name, q, limit, offset
- `+"`api_request`"+`: path* | query_params, limit, offset
(* = required)

All endpoints are read-only.

Usage (via gateway_call):
`+"```"+`
gateway_call("netbox.get_devices", {"status": "active", "site": "dc-1"}, "%s")
gateway_call("netbox.get_device", {"id": 42}, "%s")
gateway_call("netbox.get_interfaces", {"device": "edge-router-1"}, "%s")
gateway_call("netbox.get_ip_addresses", {"address": "10.0.0.1/24"}, "%s")
gateway_call("netbox.get_prefixes", {"site": "dc-1"}, "%s")
gateway_call("netbox.get_virtual_machines", {"cluster": "prod-cluster"}, "%s")
gateway_call("netbox.get_circuits", {"provider": "lumen"}, "%s")
gateway_call("netbox.api_request", {"path": "dcim/power-feeds/", "query_params": {"status": "active"}}, "%s")
`+"```"+`
`, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName)
	case "kubernetes":
		return fmt.Sprintf(`
**Parameters:**
- `+"`get_namespaces`"+`: label_selector, field_selector, limit
- `+"`get_pods`"+`: namespace* | name, label_selector, field_selector, limit
- `+"`get_pod_detail`"+`: namespace*, name*
- `+"`get_pod_logs`"+`: namespace*, name* | container, tail_lines, since_seconds, previous — `+"`container`"+` is required for multi-container pods
- `+"`get_events`"+`: namespace* | label_selector, field_selector, limit
- `+"`get_deployments`"+`: namespace* | name, label_selector, field_selector, limit
- `+"`get_deployment_detail`"+`: namespace*, name*
- `+"`get_statefulsets`"+`: namespace* | label_selector, field_selector, limit
- `+"`get_daemonsets`"+`: namespace* | label_selector, field_selector, limit
- `+"`get_jobs`"+`: namespace* | label_selector, field_selector, limit
- `+"`get_cronjobs`"+`: namespace* | label_selector, field_selector, limit
- `+"`get_nodes`"+`: label_selector, field_selector, limit
- `+"`get_node_detail`"+`: name*
- `+"`get_services`"+`: namespace* | label_selector, field_selector, limit
- `+"`get_configmaps`"+`: namespace* | label_selector, field_selector, limit
- `+"`get_ingresses`"+`: namespace* | label_selector, field_selector, limit
- `+"`api_request`"+`: path* | params
(* = required)

All endpoints are read-only GET requests.

Usage (via gateway_call):
`+"```"+`
gateway_call("kubernetes.get_namespaces", {}, "%s")
gateway_call("kubernetes.get_pods", {"namespace": "default", "label_selector": "app=api"}, "%s")
gateway_call("kubernetes.get_pod_detail", {"namespace": "default", "name": "api-7d9f5b4c-x2k4z"}, "%s")
gateway_call("kubernetes.get_pod_logs", {"namespace": "default", "name": "api-7d9f5b4c-x2k4z", "tail_lines": 200}, "%s")
gateway_call("kubernetes.get_events", {"namespace": "default", "field_selector": "type=Warning"}, "%s")
gateway_call("kubernetes.get_deployments", {"namespace": "default"}, "%s")
gateway_call("kubernetes.get_nodes", {}, "%s")
gateway_call("kubernetes.get_node_detail", {"name": "node-1"}, "%s")
`+"```"+`
`, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName)
	case "jira":
		return fmt.Sprintf(`
**Parameters:**
- `+"`search_issues`"+`: jql* | fields, expand, start_at, max_results
- `+"`get_issue`"+`: key* | fields, expand
- `+"`get_issue_comments`"+`: key* | start_at, max_results
- `+"`get_issue_transitions`"+`: key*
- `+"`get_issue_changelog`"+`: key* | start_at, max_results
- `+"`get_projects`"+`: start_at, max_results
- `+"`get_project`"+`: key*
- `+"`search_users`"+`: query* | start_at, max_results
- `+"`api_request`"+`: path* | params
- `+"`add_comment`"+` **(write)**: key*, body* (string on Server/DC v2; ADF object or string on Cloud v3 — strings are auto-wrapped)
- `+"`transition_issue`"+` **(write)**: key*, transition_id* | comment, fields
- `+"`create_issue`"+` **(write)**: project_key*, issue_type*, summary* | description, assignee, priority, labels (array of strings), fields
- `+"`update_issue`"+` **(write)**: key*, fields*
(* = required)
**(write)** marks methods that mutate state — they return an error unless `+"`jira_allow_writes=true`"+` is set on the instance.

Cloud (v3) and Server/DC (v2) differ in path, auth, and body shape — the tool selects the right form based on `+"`jira_api_version`"+` and `+"`jira_auth_type`"+`.

Usage (via gateway_call):
`+"```"+`
gateway_call("jira.search_issues", {"jql": "project = OPS AND status = \"In Progress\"", "max_results": 25}, "%s")
gateway_call("jira.get_issue", {"key": "OPS-1234"}, "%s")
gateway_call("jira.get_issue_comments", {"key": "OPS-1234"}, "%s")
gateway_call("jira.get_issue_transitions", {"key": "OPS-1234"}, "%s")
gateway_call("jira.get_projects", {}, "%s")
gateway_call("jira.search_users", {"query": "alice"}, "%s")
gateway_call("jira.add_comment", {"key": "OPS-1234", "body": "Investigating elevated 5xx rate"}, "%s")
gateway_call("jira.transition_issue", {"key": "OPS-1234", "transition_id": "31"}, "%s")
gateway_call("jira.create_issue", {"project_key": "OPS", "issue_type": "Incident", "summary": "Disk usage > 90%%", "labels": ["prod", "urgent"]}, "%s")
`+"```"+`
`, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName, logicalName)
	default:
		return fmt.Sprintf("Use `gateway_call(\"%s.<tool_method>\", {<args>}, \"%s\")` to call this tool's methods.\n", typeName, logicalName)
	}
}

// extractToolDetails extracts non-secret, agent-relevant details from a tool instance's settings.
// For SSH: lists configured hostnames so the agent knows which servers it can target.
// For other tool types (zabbix, etc.): no extra details needed — the agent interacts via MCP Gateway
// tools and doesn't need internal connection details like URLs or endpoints.
func extractToolDetails(tool database.ToolInstance) string {
	if tool.Settings == nil {
		return ""
	}

	typeName := tool.ToolType.Name

	switch typeName {
	case "ssh":
		var details strings.Builder

		// Extract hostnames from ssh_hosts array — agent needs these for server targeting
		hostsData, ok := tool.Settings["ssh_hosts"]
		if ok {
			hostsJSON, err := json.Marshal(hostsData)
			if err == nil {
				var hosts []map[string]interface{}
				if err := json.Unmarshal(hostsJSON, &hosts); err == nil {
					var hostnames []string
					for _, h := range hosts {
						// Skip placeholder rows with blank addresses (same filter as runtime)
						if addr, _ := h["address"].(string); strings.TrimSpace(addr) == "" {
							continue
						}
						if hostname, ok := h["hostname"].(string); ok && hostname != "" {
							hostnames = append(hostnames, hostname)
						}
					}
					if len(hostnames) > 0 {
						details.WriteString(fmt.Sprintf("Configured hosts: %s\n", strings.Join(hostnames, ", ")))
					}
				}
			}
		}

		// Note ad-hoc connection capability when enabled
		if allow, ok := tool.Settings["allow_adhoc_connections"].(bool); ok && allow {
			user := "root"
			if u, ok := tool.Settings["adhoc_default_user"].(string); ok && u != "" {
				user = u
			}
			port := 22
			if p, ok := tool.Settings["adhoc_default_port"].(float64); ok && p > 0 {
				port = int(p)
			}
			details.WriteString(fmt.Sprintf("Ad-hoc connections enabled: can connect to any server (default user: %s, port: %d)\n", user, port))
			if allowWrite, ok := tool.Settings["adhoc_allow_write_commands"].(bool); ok && allowWrite {
				details.WriteString("Ad-hoc write commands: allowed\n")
			} else {
				details.WriteString("Ad-hoc write commands: read-only (diagnostic commands only)\n")
			}
		}

		return details.String()
	}

	return ""
}

// truncateString truncates a string to max rune length, safe for multi-byte UTF-8
func truncateString(s string, max int) string {
	runes := []rune(s)
	if len(runes) <= max {
		return s
	}
	if max < 4 {
		return string(runes[:max])
	}
	return string(runes[:max-3]) + "..."
}
